=== llennchan/ddlc-jetbrains-theme/src/main/resources/theme-schema/doki.theme.schema.json
{
  "version": "1.0",
  "definitions": {
    "color": {
      "type": "string",
      "pattern": "^#[0-9a-fA-F]{6}([0-9a-fA-F]{2})?$",
      "title": "Color",
      "description": "Color in #RRGGBB format",
      "examples": [
        "#123abc"
      ]
    },
    "sticker": {
      "type": "string",
      "pattern": "^.+\\.png$",
      "title": "Sticker File Name",
      "description": "The name of the background image that is in the same directory as the definition",
      "default": "just_monika.png",
      "examples": [
        "just_monika.png"
      ]
    }
  },
  "type": "object",
  "$schema": "http://json-schema.org/draft-07/schema#",
  "required": [
    "id",
    "name",
    "displayName",
    "dark",
    "author",
    "stickers",
    "group",
    "ui"
  ],
  "properties": {
    "id": {
      "type": "string",
      "title": "Theme Id",
      "description": "Unique Identifier for the theme.",
      "default": "",
      "pattern": "^[0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{12}$",
      "examples": [
        "91415015-8fe3-48eb-9951-70a5cd6cbb7f",
        "a14733d6-8e15-4e75-b6b8-509f323e5b3b"
      ]
    },
    "name": {
      "type": "string",
      "title": "Theme name",
      "description": "Theme name",
      "default": "",
      "examples": [
        "My Brand New Theme"
      ]
    },
    "displayName": {
      "type": "string",
      "title": "Display name",
      "description": "The name used in various theme components such as the Status Bar",
      "default": "",
      "examples": [
        "Just Monika"
      ]
    },
    "dark": {
      "type": "boolean",
      "title": "Dark theme",
      "description": "If 'true' then Darcula theme will be used as the base for modification, otherwise Light theme will be used.",
      "default": false,
      "examples": [
        true
      ]
    },
    "author": {
      "type": "string",
      "title": "Theme author",
      "description": "The author of the theme",
      "default": "",
      "examples": [
        "Leroy Jenkins"
      ]
    },
    "editorScheme": {
      "type": "object",
      "title": "The code colors",
      "required": [
        "type"
      ],
      "properties": {
        "type": {
          "type": "string",
          "description": "How you want to create the theme xml file.",
          "pattern": "(templateExtension)|(template)|(custom)",
          "default": "template",
          "examples": [
            "template",
            "templateExtension",
            "custom"
          ]
        },
        "file": {
          "type": "string",
          "description": "The name of the file you want to extend, take as template, or use directly.",
          "pattern": "^.+\\.xml$",
          "examples": [
            "Doki Light",
            "Doki Dark",
            "Natsuki_Light.xml",
            "Yuri_Dark.xml"
          ],
          "default": "Doki Light.xml"
        }
      }
    },
    "ui": {
      "type": "object"
    },
    "group": {
      "type": "string",
      "title": "Theme Group",
      "description": "The group the theme belongs to",
      "default": "",
      "examples": [
        "Literature Club"
      ]
    },
    "stickers": {
      "type": "object",
      "required": [
        "default"
      ],
      "title": "Sticker",
      "description": "The image reference to the sticker for the bottom right hand corner.",
      "properties": {
        "default": {
          "$ref": "#/definitions/sticker"
        }      ,
        "secondary": {
          "$ref": "#/definitions/sticker"
        }
      }
    },
    "icons": {
      "type": "object",
      "patternProperties": {
        "^/": {
          "type": "string",
          "pattern": "^/"
        },
        "^[^/]": {
          "type": "object",
          "patternProperties": {
            "^/": {
              "type": "string",
              "pattern": "^/"
            }
          }
        }
      },
      "properties": {
        "ColorPalette": {
          "type": "object",
          "properties": {
            "Actions.Red": {
              "$ref": "#/definitions/color",
              "description": "Action colors are for icons that appear on toolbars"
            },
            "Actions.Yellow": {
              "$ref": "#/definitions/color"
            },
            "Actions.Green": {
              "$ref": "#/definitions/color"
            },
            "Actions.Blue": {
              "$ref": "#/definitions/color"
            },
            "Actions.Grey": {
              "$ref": "#/definitions/color"
            },
            "Actions.GreyInline": {
              "$ref": "#/definitions/color",
              "description": "Light-gray icons at the right side in input fields and combo boxes"
            },
            "Actions.GreyInline.Dark": {
              "$ref": "#/definitions/color",
              "description": "Use for dark themes"
            },
            "Objects.Grey": {
              "$ref": "#/definitions/color",
              "description": "Object colors are for icons in lists and trees"
            },
            "Objects.Blue": {
              "$ref": "#/definitions/color"
            },
            "Objects.Green": {
              "$ref": "#/definitions/color"
            },
            "Objects.Yellow": {
              "$ref": "#/definitions/color"
            },
            "Objects.YellowDark": {
              "$ref": "#/definitions/color"
            },
            "Objects.Purple": {
              "$ref": "#/definitions/color"
            },
            "Objects.Pink": {
              "$ref": "#/definitions/color"
            },
            "Objects.Red": {
              "$ref": "#/definitions/color"
            },
            "Objects.RedStatus": {
              "$ref": "#/definitions/color"
            },
            "Objects.GreenAndroid": {
              "$ref": "#/definitions/color"
            },
            "Objects.BlackText": {
              "$ref": "#/definitions/color"
            },
            "Checkbox.Background.Default": {
              "$ref": "#/definitions/color",
              "description": "An unchecked checkbox or radio button"
            },
            "Checkbox.Border.Default": {
              "$ref": "#/definitions/color"
            },
            "Checkbox.Background.Selected": {
              "$ref": "#/definitions/color",
              "description": "A checked checkbox or radio button"
            },
            "Checkbox.Border.Selected": {
              "$ref": "#/definitions/color"
            },
            "Checkbox.Foreground.Selected": {
              "$ref": "#/definitions/color"
            },
            "Checkbox.Background.Disabled": {
              "$ref": "#/definitions/color",
              "description": "A disabled checkbox or radio button"
            },
            "Checkbox.Border.Disabled": {
              "$ref": "#/definitions/color"
            },
            "Checkbox.Foreground.Disabled": {
              "$ref": "#/definitions/color"
            },
            "Checkbox.Focus.Thin.Default": {
              "$ref": "#/definitions/color",
              "description": "1px inner border in the focused state"
            },
            "Checkbox.Focus.Thin.Selected": {
              "$ref": "#/definitions/color"
            },
            "Checkbox.Focus.Wide": {
              "$ref": "#/definitions/color",
              "description": "2px outer border in the focused state"
            },
            "Checkbox.Background.Default.Dark": {
              "$ref": "#/definitions/color",
              "description": "Use for dark themes"
            },
            "Checkbox.Border.Default.Dark": {
              "$ref": "#/definitions/color",
              "description": "Use for dark themes"
            },
            "Checkbox.Background.Selected.Dark": {
              "$ref": "#/definitions/color",
              "description": "Use for dark themes"
            },
            "Checkbox.Border.Selected.Dark": {
              "$ref": "#/definitions/color",
              "description": "Use for dark themes"
            },
            "Checkbox.Foreground.Selected.Dark": {
              "$ref": "#/definitions/color",
              "description": "Use for dark themes"
            },
            "Checkbox.Background.Disabled.Dark": {
              "$ref": "#/definitions/color",
              "description": "Use for dark themes"
            },
            "Checkbox.Border.Disabled.Dark": {
              "$ref": "#/definitions/color",
              "description": "Use for dark themes"
            },
            "Checkbox.Foreground.Disabled.Dark": {
              "$ref": "#/definitions/color",
              "description": "Use for dark themes"
            },
            "Checkbox.Focus.Thin.Default.Dark": {
              "$ref": "#/definitions/color",
              "description": "Use for dark themes"
            },
            "Checkbox.Focus.Thin.Selected.Dark": {
              "$ref": "#/definitions/color",
              "description": "Use for dark themes"
            },
            "Checkbox.Focus.Wide.Dark": {
              "$ref": "#/definitions/color",
              "description": "Use for dark themes"
            }
          }
        }
      }
    },
    "colors" : {
      "type": "object",
      "title": "Theme Color Palette",
      "description": "Define common colors here and use color names in 'ui' section instead of #rrggbb values",
      "required": [
        "baseIconColor",
        "ghostColor",
        "contrastColor",
        "nonProjectFileScopeColor",
        "editorBackground",
        "secondaryBackground",
        "selectionForeground",
        "inactiveBackground",
        "inactiveBackgroundDarker",
        "headerColor",
        "baseBackground",
        "borderColor",
        "buttonColor",
        "selectionInactive",
        "tagColor",
        "secondaryForegroundColor",
        "selectionBackground",
        "buttonFont",
        "foregroundColor",
        "startColor",
        "highlightColor",
        "disabledColor",
        "accentColorTransparent",
        "accentColorLessTransparent",
        "accentColorMoreTransparent",
        "accentColor",
        "accentContrastColor",
        "stopColor",
        "testScopeColor",
        "popupMask",
        "codeBlock",
        "textEditorBackground",
        "searchResultBackground",
        "classNameColor",
        "htmlTagColor",
        "stringColor",
        "keyColor",
        "keywordColor"
      ],
      "patternProperties": {
        "baseIconColor": {
          "$ref": "#/definitions/color"
        },
        "ghostColor": {
          "$ref": "#/definitions/color"
        },
        "contrastColor": {
          "$ref": "#/definitions/color"
        },
        "nonProjectFileScopeColor": {
          "$ref": "#/definitions/color"
        },
        "editorBackground": {
          "$ref": "#/definitions/color"
        },
        "secondaryBackground": {
          "$ref": "#/definitions/color"
        },
        "selectionForeground": {
          "$ref": "#/definitions/color"
        },
        "inactiveBackground": {
          "$ref": "#/definitions/color"
        },
        "inactiveBackgroundDarker": {
          "$ref": "#/definitions/color"
        },
        "headerColor": {
          "$ref": "#/definitions/color"
        },
        "baseBackground": {
          "$ref": "#/definitions/color"
        },
        "borderColor": {
          "$ref": "#/definitions/color"
        },
        "buttonColor": {
          "$ref": "#/definitions/color"
        },
        "selectionInactive": {
          "$ref": "#/definitions/color"
        },
        "tagColor": {
          "$ref": "#/definitions/color"
        },
        "secondaryForegroundColor": {
          "$ref": "#/definitions/color"
        },
        "selectionBackground": {
          "$ref": "#/definitions/color"
        },
        "buttonFont": {
          "$ref": "#/definitions/color"
        },
        "foregroundColor": {
          "$ref": "#/definitions/color"
        },
        "startColor": {
          "$ref": "#/definitions/color"
        },
        "highlightColor": {
          "$ref": "#/definitions/color"
        },
        "disabledColor": {
          "$ref": "#/definitions/color"
        },
        "accentColorTransparent": {
          "$ref": "#/definitions/color"
        },
        "accentColorLessTransparent": {
          "$ref": "#/definitions/color"
        },
        "accentColorMoreTransparent": {
          "$ref": "#/definitions/color"
        },
        "accentColor": {
          "$ref": "#/definitions/color"
        },
        "accentContrastColor": {
          "$ref": "#/definitions/color"
        },
        "stopColor": {
          "$ref": "#/definitions/color"
        },
        "testScopeColor": {
          "$ref": "#/definitions/color"
        },
        "popupMask": {
          "$ref": "#/definitions/color"
        },
        "codeBlock": {
          "$ref": "#/definitions/color"
        },
        "textEditorBackground": {
          "$ref": "#/definitions/color"
        },
        "searchResultBackground": {
          "$ref": "#/definitions/color"
        },
        "classNameColor": {
          "$ref": "#/definitions/color"
        },
        "htmlTagColor": {
          "$ref": "#/definitions/color"
        },
        "stringColor": {
          "$ref": "#/definitions/color"
        },
        "keyColor": {
          "$ref": "#/definitions/color"
        },
        "keywordColor": {
          "$ref": "#/definitions/color"
        },
        ".*": {
          "$ref": "#/definitions/color"
        }
      }
    }
  }
}

=== llennchan/ddlc-jetbrains-theme/themes/definitions/konoSuba/megumin.doki.json
{
  "id": "63fe4617-4cac-47a5-9b93-6794514c35ad",
  "name": "Megumin",
  "displayName": "Megumin",
  "dark": true,
  "author": "cyclic-reference",
  "group": "KonoSuba",
  "editorScheme": {
    "type": "templateExtension",
    "file": "Megumin.xml"
  },
  "stickers": {
    "default": "megumin.png"
  },
  "colors": {
    "baseIconColor": "#979087",
    "ghostColor": "#FFFFFF00",
    "contrastColor": "#2e2b32",
    "nonProjectFileScopeColor":  "#312A26",
    "editorBackground": "#2f2329",
    "secondaryBackground": "#2f2329",
    "selectionForeground": "#E2CB14",
    "inactiveBackground": "#2a272e",
    "inactiveBackgroundDarker": "#333037",
    "headerColor": "#2f2329",
    "baseBackground": "#271c21",
    "borderColor": "#32262c",
    "buttonColor":  "#2f2329",
    "selectionInactive": "#2a272e",
    "tagColor": "#7A7A7A",
    "secondaryForegroundColor": "#766B6B",
    "selectionBackground":  "#563036",
    "selectionBackgroundTransparent":  "#563036A5",
    "buttonFont": "#766B6B",
    "foregroundColor":  "#bbbbbb",
    "startColor":  "#6c341d",
    "highlightColor": "#a32f345a",
    "disabledColor": "#585F6F",
    "accentColorTransparent": "#CCA3315A",
    "accentColorLessTransparent": "#CCA3319A",
    "accentColorMoreTransparent": "#CCA3312A",
    "accentColor": "#CCA331",
    "accentContrastColor": "#271c21",
    "stopColor": "#eeb416",
    "testScopeColor": "#243125",
    "popupMask": "#EAEAF00A",
    "codeBlock": "#2f2329",
    "textEditorBackground": "#2f2329",
    "searchResultBackground": "#2A272E",
    "classNameColor": "#dae838",
    "htmlTagColor": "#a28a92",
    "stringColor": "#ffd866",
    "keyColor": "#a28a92",
    "keywordColor": "#a28a92"
  },
  "ui": {},
  "icons": {}
}

=== llennchan/ddlc-jetbrains-theme/themes/definitions/mistress/wyla/wyla.doki.json
{
  "id": "9f62362a-49e0-4b82-8f63-d1f98ae7799f",
  "name": "Wyla",
  "displayName": "Wyla",
  "dark": true,
  "author": "cyclic-reference",
  "group": "Mistress",
  "editorScheme": {
    "type": "custom",
    "file": "Wyla.xml"
  },
  "stickers": {
    "default": "wyla.png"
  },
  "colors": {
    "baseIconColor": "#979087",
    "ghostColor": "#FFFFFF00",
    "contrastColor": "#2e2b32",
    "nonProjectFileScopeColor":  "#312A26",
    "editorBackground": "#2f2329",
    "secondaryBackground": "#2f2329",
    "selectionForeground": "#E2CB14",
    "inactiveBackground": "#2a272e",
    "inactiveBackgroundDarker": "#333037",
    "headerColor": "#2f2329",
    "baseBackground": "#271c21",
    "borderColor": "#2b2a32",
    "buttonColor":  "#2f2329",
    "selectionInactive": "#2a272e",
    "tagColor": "#7A7A7A",
    "secondaryForegroundColor": "#766B6B",
    "selectionBackground":  "#40434c",
    "selectionBackgroundTransparent":  "#40434cA5",
    "buttonFont": "#766B6B",
    "foregroundColor":  "#bbbbbb",
    "startColor":  "#6c341d",
    "highlightColor": "#403033",
    "disabledColor": "#585F6F",
    "accentColorTransparent": "#CCA3315A",
    "accentColorLessTransparent": "#CCA3319A",
    "accentColorMoreTransparent": "#CCA3312A",
    "accentColor": "#CCA331",
    "accentContrastColor": "#271c21",
    "stopColor": "#eeb416",
    "testScopeColor": "#243125",
    "popupMask": "#EAEAF00A",
    "codeBlock": "#2f2329",
    "textEditorBackground": "#2f2329",
    "searchResultBackground": "#2A272E",
    "classNameColor": "#dae838",
    "htmlTagColor": "#a28a92",
    "stringColor": "#ffd866",
    "keyColor": "#a28a92",
    "keywordColor": "#a28a92"
  },
  "ui": {},
  "icons": {}
}

=== llennchan/ddlc-jetbrains-theme/themes/definitions/mistress/syrena/syrena.doki.json
{
  "id": "c8df9413-5d9f-4e0c-ae64-5d5c1cffe9a5",
  "name": "Syrena",
  "displayName": "Syrena",
  "dark": true,
  "author": "cyclic-reference",
  "group": "Mistress",
  "editorScheme": {
    "type": "custom",
    "file": "Syrena.xml"
  },
  "stickers": {
    "default": "syrena.png"
  },
  "colors": {
    "baseIconColor": "#97818B",
    "ghostColor": "#FFFFFF00",
    "contrastColor": "#392525",
    "nonProjectFileScopeColor":  "#452f25",
    "editorBackground": "#3A2525",
    "secondaryBackground": "#392524",
    "selectionForeground": "#ffffff",
    "inactiveBackground": "#49434c",
    "inactiveBackgroundDarker": "#3c373f",
    "headerColor": "#362222",
    "baseBackground": "#321f1f",
    "borderColor": "#3c292b",
    "buttonColor": "#422c2c",
    "selectionInactive": "#543939",
    "tagColor": "#7A7A7A",
    "secondaryForegroundColor": "#B9AA9F",
    "selectionBackground":  "#564135",
    "selectionBackgroundTransparent":  "#564135A5",
    "buttonFont": "#B9AA9F",
    "foregroundColor": "#bbbbbb",
    "startColor":  "#972e26",
    "highlightColor": "#433330",
    "disabledColor": "#7F818F",
    "accentColorTransparent": "#FD7C4B5A",
    "accentColorLessTransparent": "#FD7C4B9A",
    "accentColorMoreTransparent": "#FD7C4B2A",
    "accentColor": "#FD7C4B",
    "accentContrastColor": "#321f1f",
    "stopColor": "#fd7c4b",
    "testScopeColor": "#29392C",
    "popupMask": "#EAEAF009",
    "codeBlock": "#362222",
    "textEditorBackground": "#3A2525",
    "searchResultBackground": "#532717",
    "classNameColor": "#E85160",
    "htmlTagColor": "#F59762",
    "stringColor": "#ffd866",
    "keyColor": "#b9a491",
    "keywordColor": "#F59762"
  },
  "ui": {},
  "icons": {}
}

=== llennchan/ddlc-jetbrains-theme/themes/definitions/mistress/eleniel/eleniel.doki.json
{
  "id": "c915211e-faab-4696-8af2-230892052ba6",
  "name": "Eleniel",
  "displayName": "Eleniel",
  "dark": true,
  "author": "cyclic-reference",
  "group": "Mistress",
  "editorScheme": {
    "type": "custom",
    "file": "Eleniel.xml"
  },
  "stickers": {
    "default": "eleniel.png"
  },
  "colors": {
    "baseIconColor": "#808597",
    "ghostColor": "#FFFFFF00",
    "contrastColor": "#2e2b32",
    "nonProjectFileScopeColor":  "#483d3e",
    "editorBackground": "#3B3541",
    "secondaryBackground": "#3e3642",
    "selectionForeground": "#ffffff",
    "inactiveBackground": "#49434c",
    "inactiveBackgroundDarker": "#3c373f",
    "headerColor": "#3B3541",
    "baseBackground": "#3B3541",
    "borderColor": "#3f393f",
    "buttonColor": "#443e48",
    "selectionInactive": "#4c454f",
    "tagColor": "#7A7A7A",
    "secondaryForegroundColor": "#9e9199",
    "selectionBackground":  "#58515C",
    "selectionBackgroundTransparent":  "#58515C",
    "buttonFont": "#91858c",
    "foregroundColor":  "#bbbbbb",
    "startColor":  "#6e6773",
    "highlightColor": "#4b4351",
    "disabledColor": "#525C6F",
    "accentColorTransparent": "#52C4E65A",
    "accentColorLessTransparent": "#52C4E69A",
    "accentColorMoreTransparent": "#52C4E62A",
    "accentColor": "#52C4E6",
    "accentContrastColor": "#2e2b32",
    "stopColor": "#76ffff",
    "testScopeColor": "#3A5841",
    "popupMask": "#EAEAF020",
    "codeBlock": "#39363F",
    "textEditorBackground": "#403D46",
    "searchResultBackground": "#4c454f",
    "classNameColor": "#AA9BEF",
    "htmlTagColor": "#bca3aa",
    "stringColor": "#f1fa8c",
    "keyColor": "#bca3aa",
    "keywordColor": "#bca3aa"
  },
  "ui": {},
  "icons": {}
}

=== llennchan/ddlc-jetbrains-theme/themes/definitions/killLaKill/ryuko/ryuko.doki.json
{
  "id": "19b65ec8-133c-4655-a77b-13623d8e97d3",
  "name": "Ryuko",
  "displayName": "Ryuko",
  "dark": true,
  "author": "cyclic-reference",
  "group": "Kill la Kill",
  "editorScheme": {
    "type": "template",
    "name": "Doki Dark"
  },
  "stickers": {
    "default": "ryuko.png",
    "secondary": "ryuko_senketsu.png"
  },
  "colors": {
    "baseIconColor": "#717981",
    "ghostColor": "#FFFFFF00",
    "contrastColor": "#262c32",
    "nonProjectFileScopeColor":  "#373c39",
    "editorBackground": "#2f2329",
    "secondaryBackground": "#282f35",
    "selectionForeground": "#E2CB14",
    "inactiveBackground": "#2a272e",
    "inactiveBackgroundDarker": "#333037",
    "headerColor": "#2b3238",
    "baseBackground": "#2f363c",
    "borderColor": "#2e353a",
    "buttonColor": "#2b3237",
    "selectionInactive": "#292e34",
    "tagColor": "#7A7A7A",
    "secondaryForegroundColor": "#766B6B",
    "selectionBackground":  "#403033",
    "selectionBackgroundTransparent":  "#403033A5",
    "buttonFont": "#766B6B",
    "foregroundColor":  "#bbbbbb",
    "startColor": "#511c22",
    "highlightColor": "#403033",
    "disabledColor": "#585F6F",
    "accentColorTransparent": "#a730355A",
    "accentColorLessTransparent": "#a730359A",
    "accentColorMoreTransparent": "#a730352A",
    "accentColor": "#a73035",
    "accentContrastColor": "#271c21",
    "stopColor": "#ee2726",
    "testScopeColor": "#2d3e3a",
    "popupMask": "#EAEAF00A",
    "codeBlock": "#2f2329",
    "textEditorBackground": "#2b3238",
    "searchResultBackground": "#2A272E",
    "classNameColor": "#dae838",
    "htmlTagColor": "#a28a92",
    "stringColor": "#ffd866",
    "keyColor": "#a28a92",
    "keywordColor": "#a28a92"
  },
  "ui": {},
  "icons": {}
}

=== llennchan/ddlc-jetbrains-theme/themes/definitions/mistress/sanya/sanya.doki.json
{
  "id": "436ff3a0-4072-4b38-8d6f-888b18b5d0ab",
  "name": "Sanya",
  "displayName": "Sanya",
  "dark": true,
  "author": "cyclic-reference",
  "group": "Mistress",
  "editorScheme": {
    "type": "custom",
    "file": "Sanya.xml"
  },
  "stickers": {
    "default": "sanya.png"
  },
  "colors": {
    "ghostColor": "#FFFFFF00",
    "contrastColor": "#341F2D",
    "nonProjectFileScopeColor":  "#413037",
    "editorBackground": "#362839",
    "secondaryBackground": "#382639",
    "selectionForeground": "#ffffff",
    "inactiveBackground": "#49434c",
    "inactiveBackgroundDarker": "#3c373f",
    "headerColor": "#3d2536",
    "baseBackground": "#3a2333",
    "borderColor": "#432E3D",
    "buttonColor": "#341F2D",
    "selectionInactive": "#883552",
    "tagColor": "#7A7A7A",
    "secondaryForegroundColor": "#9e9199",
    "selectionBackground":  "#af1f51",
    "selectionBackgroundTransparent":  "#af1f5155",
    "buttonFont": "#bbbbbb",
    "foregroundColor": "#b5a3b0",
    "startColor":  "#6d4466",
    "highlightColor": "#403046",
    "disabledColor": "#525C6F",
    "accentColorTransparent": "#C6FF005A",
    "accentColorLessTransparent": "#C6FF009A",
    "accentColorMoreTransparent": "#C6FF002A",
    "accentColor": "#C6FF00",
    "accentContrastColor": "#362839",
    "stopColor": "#ec1f62",
    "testScopeColor": "#28382D",
    "popupMask": "#EAEAF009",
    "baseIconColor": "#6B678A",
    "codeBlock": "#322130",
    "textEditorBackground": "#382536",
    "searchResultBackground": "#4C294A",
    "classNameColor": "#c1ff10",
    "htmlTagColor": "#BD84DD",
    "stringColor": "#f1fa8c",
    "keyColor": "#BD84DD",
    "keywordColor": "#BD84DD"
  },
  "ui": {},
  "icons": {}
}

=== llennchan/ddlc-jetbrains-theme/themes/definitions/literature/natsuki/light/natsuki.light.doki.json
{
  "id": "91415015-8fe3-48eb-9951-70a5cd6cbb7f",
  "name": "Natsuki Light",
  "displayName": "Natsuki",
  "dark": false,
  "author": "cyclic-reference",
  "group": "Literature Club",
  "editorScheme": {
    "type": "templateExtension",
    "file": "Natsuki_Light.xml"
  },
  "stickers": {
    "default": "natsuki.png",
    "secondary": "natsuki_joy.png"
  },
  "colors": {
    "baseIconColor": "#7F707A",
    "ghostColor": "#FFFFFF00",
    "contrastColor": "#f0c3e3",
    "nonProjectFileScopeColor": "#FFE4E3",
    "editorBackground": "#f0d4e1",
    "secondaryBackground": "#f3cfe0",
    "selectionForeground": "#ffffff",
    "inactiveBackground": "#eed4ec",
    "inactiveBackgroundDarker": "#ebd1e9",
    "headerColor": "#FFE0F0",
    "baseBackground": "#fbdde9",
    "borderColor": "#F1D7E6",
    "buttonColor": "#e5c5d3",
    "selectionInactive": "#FFD9E2",
    "tagColor": "#7A7A7A",
    "secondaryForegroundColor": "#36363A",
    "selectionBackground": "#dc99bb",
    "buttonFont": "#252427",
    "foregroundColor":  "#000000",
    "startColor":  "#F25AAF",
    "highlightColor": "#f7d2e8",
    "disabledColor": "#cbb1c6",
    "accentColorTransparent": "#E946865A",
    "accentColorLessTransparent": "#E946869A",
    "accentColorMoreTransparent": "#E946862A",
    "accentColor": "#E94686",
    "accentContrastColor": "#252427",
    "stopColor": "#fbadff",
    "testScopeColor": "#ede8e4",
    "popupMask": "#EAEAF030",

    "codeBlock": "#FDD8FF",
    "textEditorBackground": "#FFE5F1",
    "searchResultBackground": "#F1E5FA",
    "classNameColor": "#df81b8",
    "htmlTagColor": "#7B6970",
    "stringColor": "#DC872E",
    "keyColor": "#7C75EF",
    "keywordColor": "#C869A3"
  },
  "ui": {
    "CompletionPopup.background": "testScopeColor",
    "CompletionPopup.selectionForeground": "selectionForeground",
    "CompletionPopup.selectionBackground": "selectionBackground",
    "CompletionPopup.selectionInactiveBackground": "selectionBackground",

    "SearchEverywhere.Tab.selectedBackground": "selectionBackground",
    "SearchEverywhere.Header.background": "headerColor",
    "SearchEverywhere.SearchField.background": "headerColor"
  },
  "icons": {}
}

=== llennchan/ddlc-jetbrains-theme/themes/definitions/reZero/rem/rem.doki.json
{
  "id": "f770dcfc-f41e-4b49-aa17-66e9ffc208fd",
  "name": "Rem",
  "displayName": "Rem",
  "dark": true,
  "author": "cyclic-reference",
  "group": "Re Zero",
  "editorScheme": {
    "type": "template",
    "name": "Doki Dark"
  },
  "stickers": {
    "default": "rem.png"
  },
  "colors": {
    "baseIconColor": "#717981",
    "ghostColor": "#FFFFFF00",
    "contrastColor": "#30373d",
    "nonProjectFileScopeColor": "#313332",
    "editorBackground": "#2f3036",
    "secondaryBackground": "#313239",
    "selectionForeground": "#fbfbfb",
    "inactiveBackground": "#2a272e",
    "inactiveBackgroundDarker": "#333037",
    "headerColor": "#2c2d33",
    "baseBackground": "#292A30",
    "borderColor": "#2d3439",
    "buttonColor": "#323337",
    "selectionInactive": "#3a3f44",
    "tagColor": "#7A7A7A",
    "secondaryForegroundColor": "#68383d",
    "selectionBackground": "#4C637A",
    "selectionBackgroundTransparent":  "#4C637AAA",
    "buttonFont": "#6b8b99",
    "foregroundColor":  "#bbbbbb",
    "startColor": "#595959",
    "highlightColor": "#35363c",
    "disabledColor": "#585F6F",
    "accentColorTransparent": "#578CDA5A",
    "accentColorLessTransparent": "#578CDA9A",
    "accentColorMoreTransparent": "#578CDA2A",
    "accentColor": "#578CDA",
    "accentContrastColor": "#271c21",
    "stopColor": "#688dee",
    "testScopeColor": "#2c3436",
    "popupMask": "#EAEAF00A",
    "codeBlock": "#292e34",
    "textEditorBackground": "#2f3036",
    "searchResultBackground": "#272e34",
    "classNameColor": "#ef2066",
    "htmlTagColor": "#a28a92",
    "stringColor": "#f4fa8c",
    "keyColor": "#6d7ac9",
    "keywordColor": "#bd84dd"
  },
  "ui": {},
  "icons": {}
}
