=== llennchan/ddlc-jetbrains-theme/src/main/resources/theme-schema/doki.theme.schema.json
{
  "version": "1.0",
  "definitions": {
    "color": {
      "type": "string",
      "pattern": "^#[0-9a-fA-F]{6}([0-9a-fA-F]{2})?$",
      "title": "Color",
      "description": "Color in #RRGGBB format",
      "examples": [
        "#123abc"
      ]
    },
    "sticker": {
      "type": "string",
      "pattern": "^.+\\.png$",
      "title": "Sticker File Name",
      "description": "The name of the background image that is in the same directory as the definition",
      "default": "just_monika.png",
      "examples": [
        "just_monika.png"
      ]
    }
  },
  "type": "object",
  "$schema": "http://json-schema.org/draft-07/schema#",
  "required": [
    "id",
    "name",
    "displayName",
    "dark",
    "author",
    "stickers",
    "group",
    "ui"
  ],
  "properties": {
    "id": {
      "type": "string",
      "title": "Theme Id",
      "description": "Unique Identifier for the theme.",
      "default": "",
      "pattern": "^[0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{12}$",
      "examples": [
        "91415015-8fe3-48eb-9951-70a5cd6cbb7f",
        "a14733d6-8e15-4e75-b6b8-509f323e5b3b"
      ]
    },
    "name": {
      "type": "string",
      "title": "Theme name",
      "description": "Theme name",
      "default": "",
      "examples": [
        "My Brand New Theme"
      ]
    },
    "displayName": {
      "type": "string",
      "title": "Display name",
      "description": "The name used in various theme components such as the Status Bar",
      "default": "",
      "examples": [
        "Just Monika"
      ]
    },
    "dark": {
      "type": "boolean",
      "title": "Dark theme",
      "description": "If 'true' then Darcula theme will be used as the base for modification, otherwise Light theme will be used.",
      "default": false,
      "examples": [
        true
      ]
    },
    "author": {
      "type": "string",
      "title": "Theme author",
      "description": "The author of the theme",
      "default": "",
      "examples": [
        "Leroy Jenkins"
      ]
    },
    "editorScheme": {
      "type": "object",
      "title": "The code colors",
      "required": [
        "type"
      ],
      "properties": {
        "type": {
          "type": "string",
          "description": "How you want to create the theme xml file.",
          "pattern": "(templateExtension)|(template)|(custom)",
          "default": "template",
          "examples": [
            "template",
            "templateExtension",
            "custom"
          ]
        },
        "file": {
          "type": "string",
          "description": "The name of the file you want to extend, take as template, or use directly.",
          "pattern": "^.+\\.xml$",
          "examples": [
            "Doki Light",
            "Doki Dark",
            "Natsuki_Light.xml",
            "Yuri_Dark.xml"
          ],
          "default": "Doki Light.xml"
        }
      }
    },
    "ui": {
      "type": "object"
    },
    "group": {
      "type": "string",
      "title": "Theme Group",
      "description": "The group the theme belongs to",
      "default": "",
      "examples": [
        "Literature Club"
      ]
    },
    "stickers": {
      "type": "object",
      "required": [
        "default"
      ],
      "title": "Sticker",
      "description": "The image reference to the sticker for the bottom right hand corner.",
      "properties": {
        "default": {
          "$ref": "#/definitions/sticker"
        }      ,
        "secondary": {
          "$ref": "#/definitions/sticker"
        }
      }
    },
    "icons": {
      "type": "object",
      "patternProperties": {
        "^/": {
          "type": "string",
          "pattern": "^/"
        },
        "^[^/]": {
          "type": "object",
          "patternProperties": {
            "^/": {
              "type": "string",
              "pattern": "^/"
            }
          }
        }
      },
      "properties": {
        "ColorPalette": {
          "type": "object",
          "properties": {
            "Actions.Red": {
              "$ref": "#/definitions/color",
              "description": "Action colors are for icons that appear on toolbars"
            },
            "Actions.Yellow": {
              "$ref": "#/definitions/color"
            },
            "Actions.Green": {
              "$ref": "#/definitions/color"
            },
            "Actions.Blue": {
              "$ref": "#/definitions/color"
            },
            "Actions.Grey": {
              "$ref": "#/definitions/color"
            },
            "Actions.GreyInline": {
              "$ref": "#/definitions/color",
              "description": "Light-gray icons at the right side in input fields and combo boxes"
            },
            "Actions.GreyInline.Dark": {
              "$ref": "#/definitions/color",
              "description": "Use for dark themes"
            },
            "Objects.Grey": {
              "$ref": "#/definitions/color",
              "description": "Object colors are for icons in lists and trees"
            },
            "Objects.Blue": {
              "$ref": "#/definitions/color"
            },
            "Objects.Green": {
              "$ref": "#/definitions/color"
            },
            "Objects.Yellow": {
              "$ref": "#/definitions/color"
            },
            "Objects.YellowDark": {
              "$ref": "#/definitions/color"
            },
            "Objects.Purple": {
              "$ref": "#/definitions/color"
            },
            "Objects.Pink": {
              "$ref": "#/definitions/color"
            },
            "Objects.Red": {
              "$ref": "#/definitions/color"
            },
            "Objects.RedStatus": {
              "$ref": "#/definitions/color"
            },
            "Objects.GreenAndroid": {
              "$ref": "#/definitions/color"
            },
            "Objects.BlackText": {
              "$ref": "#/definitions/color"
            },
            "Checkbox.Background.Default": {
              "$ref": "#/definitions/color",
              "description": "An unchecked checkbox or radio button"
            },
            "Checkbox.Border.Default": {
              "$ref": "#/definitions/color"
            },
            "Checkbox.Background.Selected": {
              "$ref": "#/definitions/color",
              "description": "A checked checkbox or radio button"
            },
            "Checkbox.Border.Selected": {
              "$ref": "#/definitions/color"
            },
            "Checkbox.Foreground.Selected": {
              "$ref": "#/definitions/color"
            },
            "Checkbox.Background.Disabled": {
              "$ref": "#/definitions/color",
              "description": "A disabled checkbox or radio button"
            },
            "Checkbox.Border.Disabled": {
              "$ref": "#/definitions/color"
            },
            "Checkbox.Foreground.Disabled": {
              "$ref": "#/definitions/color"
            },
            "Checkbox.Focus.Thin.Default": {
              "$ref": "#/definitions/color",
              "description": "1px inner border in the focused state"
            },
            "Checkbox.Focus.Thin.Selected": {
              "$ref": "#/definitions/color"
            },
            "Checkbox.Focus.Wide": {
              "$ref": "#/definitions/color",
              "description": "2px outer border in the focused state"
            },
            "Checkbox.Background.Default.Dark": {
              "$ref": "#/definitions/color",
              "description": "Use for dark themes"
            },
            "Checkbox.Border.Default.Dark": {
              "$ref": "#/definitions/color",
              "description": "Use for dark themes"
            },
            "Checkbox.Background.Selected.Dark": {
              "$ref": "#/definitions/color",
              "description": "Use for dark themes"
            },
            "Checkbox.Border.Selected.Dark": {
              "$ref": "#/definitions/color",
              "description": "Use for dark themes"
            },
            "Checkbox.Foreground.Selected.Dark": {
              "$ref": "#/definitions/color",
              "description": "Use for dark themes"
            },
            "Checkbox.Background.Disabled.Dark": {
              "$ref": "#/definitions/color",
              "description": "Use for dark themes"
            },
            "Checkbox.Border.Disabled.Dark": {
              "$ref": "#/definitions/color",
              "description": "Use for dark themes"
            },
            "Checkbox.Foreground.Disabled.Dark": {
              "$ref": "#/definitions/color",
              "description": "Use for dark themes"
            },
            "Checkbox.Focus.Thin.Default.Dark": {
              "$ref": "#/definitions/color",
              "description": "Use for dark themes"
            },
            "Checkbox.Focus.Thin.Selected.Dark": {
              "$ref": "#/definitions/color",
              "description": "Use for dark themes"
            },
            "Checkbox.Focus.Wide.Dark": {
              "$ref": "#/definitions/color",
              "description": "Use for dark themes"
            }
          }
        }
      }
    },
    "colors" : {
      "type": "object",
      "title": "Theme Color Palette",
      "description": "Define common colors here and use color names in 'ui' section instead of #rrggbb values",
      "required": [
        "baseIconColor",
        "ghostColor",
        "contrastColor",
        "nonProjectFileScopeColor",
        "editorBackground",
        "secondaryBackground",
        "selectionForeground",
        "inactiveBackground",
        "inactiveBackgroundDarker",
        "headerColor",
        "baseBackground",
        "borderColor",
        "buttonColor",
        "selectionInactive",
        "tagColor",
        "secondaryForegroundColor",
        "selectionBackground",
        "buttonFont",
        "foregroundColor",
        "startColor",
        "highlightColor",
        "disabledColor",
        "accentColorTransparent",
        "accentColorLessTransparent",
        "accentColorMoreTransparent",
        "accentColor",
        "accentContrastColor",
        "stopColor",
        "testScopeColor",
        "popupMask",
        "codeBlock",
        "textEditorBackground",
        "searchResultBackground",
        "classNameColor",
        "htmlTagColor",
        "stringColor",
        "keyColor",
        "keywordColor"
      ],
      "patternProperties": {
        "baseIconColor": {
          "$ref": "#/definitions/color"
        },
        "ghostColor": {
          "$ref": "#/definitions/color"
        },
        "contrastColor": {
          "$ref": "#/definitions/color"
        },
        "nonProjectFileScopeColor": {
          "$ref": "#/definitions/color"
        },
        "editorBackground": {
          "$ref": "#/definitions/color"
        },
        "secondaryBackground": {
          "$ref": "#/definitions/color"
        },
        "selectionForeground": {
          "$ref": "#/definitions/color"
        },
        "inactiveBackground": {
          "$ref": "#/definitions/color"
        },
        "inactiveBackgroundDarker": {
          "$ref": "#/definitions/color"
        },
        "headerColor": {
          "$ref": "#/definitions/color"
        },
        "baseBackground": {
          "$ref": "#/definitions/color"
        },
        "borderColor": {
          "$ref": "#/definitions/color"
        },
        "buttonColor": {
          "$ref": "#/definitions/color"
        },
        "selectionInactive": {
          "$ref": "#/definitions/color"
        },
        "tagColor": {
          "$ref": "#/definitions/color"
        },
        "secondaryForegroundColor": {
          "$ref": "#/definitions/color"
        },
        "selectionBackground": {
          "$ref": "#/definitions/color"
        },
        "buttonFont": {
          "$ref": "#/definitions/color"
        },
        "foregroundColor": {
          "$ref": "#/definitions/color"
        },
        "startColor": {
          "$ref": "#/definitions/color"
        },
        "highlightColor": {
          "$ref": "#/definitions/color"
        },
        "disabledColor": {
          "$ref": "#/definitions/color"
        },
        "accentColorTransparent": {
          "$ref": "#/definitions/color"
        },
        "accentColorLessTransparent": {
          "$ref": "#/definitions/color"
        },
        "accentColorMoreTransparent": {
          "$ref": "#/definitions/color"
        },
        "accentColor": {
          "$ref": "#/definitions/color"
        },
        "accentContrastColor": {
          "$ref": "#/definitions/color"
        },
        "stopColor": {
          "$ref": "#/definitions/color"
        },
        "testScopeColor": {
          "$ref": "#/definitions/color"
        },
        "popupMask": {
          "$ref": "#/definitions/color"
        },
        "codeBlock": {
          "$ref": "#/definitions/color"
        },
        "textEditorBackground": {
          "$ref": "#/definitions/color"
        },
        "searchResultBackground": {
          "$ref": "#/definitions/color"
        },
        "classNameColor": {
          "$ref": "#/definitions/color"
        },
        "htmlTagColor": {
          "$ref": "#/definitions/color"
        },
        "stringColor": {
          "$ref": "#/definitions/color"
        },
        "keyColor": {
          "$ref": "#/definitions/color"
        },
        "keywordColor": {
          "$ref": "#/definitions/color"
        },
        ".*": {
          "$ref": "#/definitions/color"
        }
      }
    }
  }
}

=== llennchan/ddlc-jetbrains-theme/themes/definitions/literature/monika/dark/monika.dark.doki.json
{
  "id": "dce48196-ff46-470c-b5f9-d1e23f4a79d3",
  "name": "Monika Dark",
  "displayName": "Monika",
  "dark": true,
  "author": "cyclic-reference",
  "editorScheme": {
    "type": "custom",
    "file": "Monika_Dark.xml"
  },
  "group": "Literature Club",
  "stickers": {
    "default": "just_monika_dark.png",
    "secondary": "just_monika_dark_joy.png"
  },
  "colors": {
    "baseIconColor": "#657F6E",
    "ghostColor": "#FFFFFF00",
    "contrastColor": "#244020",
    "nonProjectFileScopeColor": "#222613",
    "editorBackground": "#1D2115",
    "secondaryBackground": "#1a1e12",
    "selectionForeground": "#ffffff",
    "inactiveBackground": "#122D13",
    "inactiveBackgroundDarker": "#133414",
    "headerColor": "#1D2115",
    "baseBackground": "#1A1E12",
    "borderColor": "#202416",
    "buttonColor": "#1e3219",
    "selectionInactive": "#122D13",
    "tagColor": "#7A7A7A",
    "secondaryForegroundColor": "#6f9a65",
    "selectionBackground": "#30432B",
    "buttonFont": "#6f9a65",
    "foregroundColor":  "#bbbbbb",
    "startColor":  "#0abb0d",
    "highlightColor": "#253120",
    "disabledColor": "#505050",
    "accentColorTransparent": "#388E3C5A",
    "accentColorLessTransparent": "#388E3C9A",
    "accentColorMoreTransparent": "#388E3C2A",
    "accentColor": "#388E3C",
    "accentContrastColor": "#1A1E12",
    "stopColor": "#FFFA11",
    "testScopeColor": "#1b2610",
    "popupMask": "#EAEAF00A",
    "codeBlock": "#23271A",
    "textEditorBackground": "#f8f8f2",
    "searchResultBackground": "#1A401B",
    "classNameColor": "#bca3aa",
    "htmlTagColor": "#3eae5d",
    "stringColor": "#f1fa8c",
    "keyColor": "#bca3aa",
    "keywordColor": "#3eae5d"
  },
  "ui": {
    "Plugins.lightSelectionBackground": "selectionBackground",
    "CompletionPopup.selectionBackground": "selectionBackground"
  },
  "icons": {}
}

=== llennchan/ddlc-jetbrains-theme/themes/definitions/literature/sayori/dark/sayori.dark.doki.json
{
  "id": "b0340303-0a5a-4a20-9b9c-fc8ce9880078",
  "name": "Sayori Dark",
  "displayName": "Š̸̘͚̼͎̯̙̣̱̎̋̐͒a̴̖̟̠̳̤͙̟͂̂͑̐͜ỷ̵̧̨̞̠̖̠o̴̧͍̗̬̎̓͆̔͝ͅr̴̡̮̟͈͠ͅi̴̡̨͓͈̬̗̺̍́̃̇̓",
  "dark": true,
  "author": "cyclic-reference",
  "editorScheme": {
    "type": "custom",
    "file": "Sayori_Dark.xml"
  },
  "group": "Literature Club",
  "stickers": {
    "default": "sayori_dark.png",
    "secondary": "sayori_dark_normal.png"
  },
  "colors": {
    "baseIconColor": "#5B777F",
    "ghostColor": "#FFFFFF00",
    "contrastColor": "#1B323F",
    "nonProjectFileScopeColor": "#1a1c22",
    "editorBackground": "#181925",
    "secondaryBackground": "#1f2030",
    "selectionForeground": "#9CF5FF",
    "inactiveBackground": "#1b254b",
    "inactiveBackgroundDarker": "#1d2650",
    "headerColor": "#171823",
    "baseBackground": "#12131f",
    "borderColor": "#1f202d",
    "buttonColor": "#1B323F",
    "selectionInactive": "#1d274b",
    "tagColor": "#7A7A7A",
    "secondaryForegroundColor": "#111B28",
    "selectionBackground": "#234164",
    "buttonFont": "#26A8E8",
    "foregroundColor":  "#bbbbbb",
    "startColor":  "#0A74BB",
    "highlightColor": "#232e3f",
    "disabledColor": "#232323",
    "accentColorTransparent": "#00BCD45A",
    "accentColorLessTransparent": "#00BCD49A",
    "accentColorMoreTransparent": "#00BCD42A",
    "accentColor": "#00BCD4",
    "accentContrastColor": "#12131f",
    "stopColor": "#11FFFD",
    "testScopeColor": "#161c22",
    "popupMask": "#EAEAF00A",
    "codeBlock": "#1B1D31",
    "textEditorBackground": "#181925",
    "searchResultBackground": "#1D274B",
    "classNameColor": "#c1ff10",
    "htmlTagColor": "#bca3aa",
    "stringColor": "#f1fa8c",
    "keyColor": "#3F77EF",
    "keywordColor": "#bca3aa"
  },
  "ui": {
    "Plugins.lightSelectionBackground": "selectionBackground",
    "CompletionPopup.selectionBackground": "selectionBackground",
    "SearchEverywhere.Header.background": "headerColor",
    "SearchEverywhere.SearchField.background": "headerColor"
  },
  "icons": {}
}
